import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#234688ff",
    alignItems: "center",
    paddingVertical: 36,
    paddingHorizontal: 12,
    gap: 18,
  },
  homeTitle: {
    fontSize: 28,
    textAlign: "center",
    fontWeight: "bold",
    color: "#ffffffff",
    letterSpacing: 5,
    textTransform: "uppercase",
  },
  titleContainer: {
    flexDirection: "row",
    height: 70,
    alignItems: "center",
    width: "100%",
    justifyContent: "center",
  },
  monthContainer: {
    textAlign: "center",
    alignItems: "center",
    width: "60%",
  },
  year: {
    fontSize: 18,
    color: "white",
  },
  containerBills: {
    position: "relative",
    width: "100%",
    height: "80%",
    borderRadius: 18,
    padding: 12,
    backgroundColor: "#769be0ff",
  },
  containerHeader: {
    flexDirection: "row",
    width: "100%",
  },
  headerText: {
    fontSize: 24,
    height: 35,
    borderBottomWidth: 3,
    paddingHorizontal: 6,
    marginBottom: 12,
  },
  textBills: {
    fontSize: 22,
    padding: 6,
  },
  containerTotal: {
    position: "absolute",
    bottom: 0,
    left: 10,
    width: "100%",
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 3,
  },
  totalText: {
    marginLeft: 24,
    fontSize: 24,
    paddingHorizontal: 12,
    fontWeight: "bold",
  },
  containerFlatList: {
    maxHeight: "75%",
    overflow: "scroll",
  },
  btnAddBill: {
    backgroundColor: "#06df97ff",
    width: 50,
    height: 50,
    borderRadius: "50%",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  textBtn: {
    color: "white",
    fontSize: 48,
    textAlign: "center",
    marginTop: -10,
  },
});
